### ISSUE TITLE
Markdown formatting works in commands (namely /mode)

### ISSUE THREAD

**Issue by Chewsterchew** [dogancelik/irccloud-sws#10]
<img width="412" alt="706acf5adb50893893fc4a74ba597aae" src="https://user-images.githubusercontent.com/8278263/32394858-ae5d4b2a-c0ac-11e7-91c1-a9c7d003f919.png">
The command I ran is on the bottom, and the output is on top.

The ban was treated as:
_!_@an.annoying.spammer is banned
instead of
`*!*@an.annoying.spammer`

This can seriously affect banning wildcard hosts as it just italicizes it.

**Comment by dogancelik** [comment]
I could make an exception for `/mode` commands or anything that starts with a forward slash.
I will see what I can do, thanks for reporting it 😊

**Comment by dogancelik** [comment]
Okay 0b79d3beb7526c9201f6718d74dcdfebbb264ce5 should fix the issue now 😃

**Comment by Chewsterchew** [comment]
Looks good 👍
