### ISSUE TITLE
Suggestion: Add strikethrough

### ISSUE THREAD

**Issue by advaith1** [dogancelik/irccloud-sws#14]
It would be cool if we could use Send with Style to send ~~strikethrough~~ text.

**Comment by dogancelik** [comment]
IRC doesn't support strikethrough, it is possible with Unicode.
I can't add something that is not supported by IRC protocol and add more complexity to the script.

* https://saijogeorge.com/strikethrough-text-generator/
* https://www.piliapp.com/cool-text/strikethrough-text/
* https://fsymbols.com/generators/strikethrough/

You can use these generators though.
