### ISSUE TITLE
[Request] Support (some) Markdown formatting

### ISSUE THREAD

**Issue by Techman-** [dogancelik/irccloud-sws#3]
I came up with this idea fairly recently, so if some sentences don't make sense, my apologies.

IRCCloud-SWS is a nice script, but it operates off of "control" symbols like `%B` for bold, etc. I think it would be cool if the script had a "markdown" mode where if I typed something like this into the input box:
>`Trying to torrent over Tor **is** pointless`

It would get transformed (formatted) and sent to the chat as:
>Trying to torrent over Tor **is** pointless
automatically. Obviously this probably won't work well with the color, etc. formatting so the current method for formatting those things should probably be retained. Also, only a small amount of markdown should be watched for because of the nature of IRC. For example, link markdown `[]()` should be ignored, because IRC clients will never render that. For that kind of case, you could choose to not send that line at all, send just the title + link, or do something else.

Your thoughts would be appreciated.

**Comment by dogancelik** [comment]
Thanks for suggestion :+1: I can add this, but it could take a week :smiley:
Yes, we don't need link formatting because IRCCloud automatically handles them.
I think I will add only support for bold (`**`) and italic (`*`) text if that's okay :grinning:

**Comment by dogancelik** [comment]
Okay, I've added a basic Markdown feature, it only supports `***`, `**`,`*`. let's hope it doesn't break anything :smile: Please test it and give feedback :wink:

**Comment by Techman-** [comment]
Works well in my testing. I'll mention HTML tags too, but it isn't needed. Markdown doesn't have something for underlined text. You don't have to support HTML format tags either if you don't want to.

**Comment by dogancelik** [comment]
Okay, thank you for your feedback and suggestion. I've done basic testing too, I'll close this then :)
