### ISSUE TITLE
Send With Style corrupts links with certain non ascii characters. 

### ISSUE THREAD

**Issue by theholyduck** [dogancelik/irccloud-sws#4]
If you try to link a webpage that uses non ascii characters that are replaced with a %C# it will break the link and color the bits after it.

 is there some way of making the control code used to initiate this configurable. so i dont have to keep turning the feature on and off?

example link that you cant send while the script is enabled. 

https://en.wikipedia.org/wiki/Kar%C5%8Dshi

**Comment by dogancelik** [comment]
Things I can think of:

* Allow change of key `%` to something else
* Add something like (back tick)your link(back tick) that so it will not parse anything inside ` (back tick)

What do you suggest?

**Comment by theholyduck** [comment]
i mean, in a perfect world, it wouldnt use any regularly used ascii characters. it would just be a keyboard shortcut like the ctrl+c on irsii or the ctrl+k on hexchat, that just inserts the invisible ascii character. with some sort of visual indication that you just did this. 

if this really isnt an option, i think i prefer being able to set my own ascii character for you to parse.

**Comment by dogancelik** [comment]
I think a keyboard shortcut is possible. I can do this so there will be two options:

1. Auto replace %C, %B etc. with actual codes.
2. Use a keyboard shortcut to add to codes yourself.

But first I need to make sure IRCCloud is not using Ctrl+C or Ctrl+K etc.

**Comment by Eeems** [comment]
Err... IRCCloud might not be using Ctrl-C, but the OS does for copying on Windows and Linux. Might not be the best idea to use that one.

**Comment by theholyduck** [comment]
and irccloud does use ctrl+k.
irssi does use ctrl+c on linux and windows, but its in a terminal so it uses a different way of copy and pasting anyway. im not entirely sure what another viable keyboard shortcut would be

**Comment by Eeems** [comment]
Ctrl-shift-c/k is a possibility.

**Comment by dogancelik** [comment]
Firebug uses Ctrl+Shift+C, Ctrl+Shift+K opens "Jump to channel" dialog (IRCCloud bug)
Almost everything Ctrl+Shift+? used by some add-on in my Firefox, but I managed to find Ctrl+Shift+Z to be empty.

Implementation is complete. Here's how it works:
You press <kbd>Ctrl+Shift+Z</kbd> (we will change this based on consensus) then press a Style key (C for Color, B for Bold) etc.

In this example GIF, I press <kbd>Ctrl+Shift+Z</kbd> then <kbd>C</kbd> (for color)
![helloworld](https://cloud.githubusercontent.com/assets/486818/8635123/416859fc-281e-11e5-9be0-914591b8091e.gif)

**Comment by Eeems** [comment]
You may want to make the key input configurable. That way users can use whatever works best for their setup.

**Comment by dogancelik** [comment]
Yes I am going to do that actually :)

**Comment by dogancelik** [comment]
I added Keyboard Mode and waiting on your input, if everything is okay, I will close this.

The GIF above is recorded in Firefox which shows a Hex Code Block for unknown characters. Chrome doesn't show Code Blocks for unknown characters.

So don't worry when you press the master key then C and suddenly you don't see a code block for color. It's actually there but you can't see it.

**Comment by Eeems** [comment]
It might be better to switch this to have the keyboard shortcut insert %C %B etc. That way there is visible input on all browsers.

**Comment by dogancelik** [comment]
Yeah I can do that (a visual for inserted characters) with some sort of hack but why work?
