### ISSUE TITLE
Italic handling

### ISSUE THREAD

**Issue by Eeems** [dogancelik/irccloud-sws#5]
It seems that italics don't always work.

Colloquy handles \x16 as italics and \x1D does nothing
IRCCloud handles \x16 and \x1D as italics
Chatzilla doesn't handle \x16 as anything

From what I can understand via google-fu \x1D is suppose to be italics from how mIRC and most IRC clients implemented, but a few have chosen to implement it by using \x16.

**Comment by dogancelik** [comment]
I don't know which one is the most supported one. Should we change `\x16` with `\x1D`?
I tried to find some RFC about this, apparently this is not even in RFC :smiley:

**Comment by Eeems** [comment]
I believe that \x1D is more supported and less likely to cause problems with inverting then \x16. At worse it just won't italicize on someone's client instead. 
It would have been nice if these things actually had an RFC, but unfortunately it looks like nobody wants to properly standardise them.

**Comment by dogancelik** [comment]
I tested both `\x16` and `\x1D` on ChatZilla and HexChat and could not make it work on both. If a line contains any of the chars above, it just doesn't show that line on both clients. I don't know what's wrong with my computer. This is also true with bold, color codes. I'm confused :confused:

**Comment by Eeems** [comment]
Which version of ChatiZilla are you running?

**Comment by dogancelik** [comment]
ChatZilla:  `0.9.91.1`
HexChat: `2.10.2`

**Comment by Sorunome** [comment]
According to http://en.wikichip.org/wiki/irc/colors \x16 is reversing the current colors and \x1D is italics

**Comment by Eeems** [comment]
https://github.com/Sorunome/OmnomIRC2/issues/42
Some more research on this issue.
