### ISSUE TITLE
[Request] Add support for random rainbow colors

### ISSUE THREAD

**Issue by rnjohnson18** [dogancelik/irccloud-sws#6]
For example, weechat has a script where a user can type /prism and the message is sent in a colored message with, well, varying colors. Textual also has a similar option underneath their 'IRC Formatting' menus. The rainbow could be sent using %P to stand for prism.

**Comment by dogancelik** [comment]
I'll look into this after I'll implement keyboard shortcut for style codes. Thanks for your request.

**Comment by dogancelik** [comment]
![rainbow](https://cloud.githubusercontent.com/assets/486818/8671057/a21ce5f2-2a2a-11e5-9b95-1a7acee17b39.png)

I guess this is what you want, if so, you can use now: `<rainbow>your text</rainbow>`

If no complaint, I'll close this after a while. To not annoy old users, this is an optional feature and will not affect normal users at all if users don't enable "Special Functions" under SWS dialog.
