### ISSUE TITLE
[Request] Add colour menu

### ISSUE THREAD

**Issue by Eeems** [dogancelik/irccloud-sws#7]
It would be a good idea to have a colour menu of some sort pop up when a users adds %C or enters the keyboard shortcut. This way people who don't use colours enough don't have to google what the colour numbers are before sending messages.

**Comment by dogancelik** [comment]
They don't have to Google anything because I already provide the color examples.
That's why I underlined the color link.
![screenshot](https://cloud.githubusercontent.com/assets/486818/8654707/cb30cfb2-2994-11e5-8751-a23504193b91.png)

**Comment by Eeems** [comment]
Which not everybody notices. I for sure didn't notice it.
Having a visual cue as you are typing in a message is still much easier to work with then opening up the settings and looking at it in there. Assuming they know that it's there.

**Comment by dogancelik** [comment]
I will wait until we get more request for this.

**Comment by dogancelik** [comment]
Normal mode:
![colorstable1](https://cloud.githubusercontent.com/assets/486818/8670079/59bfa3f6-2a22-11e5-8cd0-27bb5fd7a3d1.gif)

Keyboard mode:
![colorstable2](https://cloud.githubusercontent.com/assets/486818/8670082/5d28a1c8-2a22-11e5-839e-a4bb52c2e2d2.gif)

I'll close this if gets no complaint.

**Comment by Eeems** [comment]
Looking good.

One thought I had while looking at it was that being able to click the numbers to insert them would be useful. I myself find it easier to just type it in (Faster), but some users might prefer to click.

Feel free to close this if you don't think that it's a good idea. Just a thought.

**Comment by dogancelik** [comment]
Okay, I'll add it then close this.
