### ISSUE TITLE
Support IRCCloud redesign

### ISSUE THREAD

**Issue by bb010g** [dogancelik/irccloud-sws#8]
The functionality still works, but you can't change any settings.

**Comment by dogancelik** [comment]
I will fix it today hopefully.

**Comment by dogancelik** [comment]
I added the dialog link under Settings menu below "Invite a friend"

![settings](https://cloud.githubusercontent.com/assets/486818/10309715/be35b5f8-6c46-11e5-842a-6802d54b76c5.png)

**Comment by Eeems** [comment]
It might look better if you put it on the other side, that or shifted the menu around and put it under the settings link.
Even better would be to embed it on the settings page as it's own option, that would be a much larger undertaking though.

**Comment by dogancelik** [comment]
I thought that would be hard but apparently it's possible so here the new version `4.0.1`

![settings2](https://cloud.githubusercontent.com/assets/486818/10321203/24c4cadc-6c80-11e5-951c-c7f29555c7fb.png)

**Comment by Eeems** [comment]
Awesome! Works great for me.
