### ISSUE TITLE
IRCCloud URL changes

### ISSUE THREAD

**Issue by c99koder** [dogancelik/irccloud-sws#9]
IRCCloud is no longer using hashes in the URLs, the new URL for your settings pane should be https://www.irccloud.com/?/settings=sendwithstyle

**Comment by c99koder** [comment]
This also affects binding the current text field when switching conversations, as the whole URL changes instead of just a hash now

**Comment by dogancelik** [comment]
I'll take a look, thanks for notifying @c99koder

**Comment by dogancelik** [comment]
Should be fixed in dd3d36f5febe3a09434f77c9004816767fdb7c97
